# Generated by Django 2.1 on 2018-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180906_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChefCookOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('problems', models.ManyToManyField(to='core.Problem')),
            ],
        ),
    ]
