# Generated by Django 2.1 on 2018-09-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_codechefcookoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=4)),
                ('penalty', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-contest_successful_submissions']},
        ),
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contest'),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
