# Generated by Django 2.1 on 2018-09-16 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180916_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
