# Generated by Django 2.1 on 2018-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submission_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
