# Generated by Django 2.1 on 2018-09-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180916_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='last_checked',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='penalty',
        ),
    ]
