# Generated by Django 2.1 on 2018-09-17 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180917_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 18, 54, 17, 235493)),
        ),
    ]
