# Generated by Django 2.1 on 2018-09-17 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180917_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 18, 54, 38, 711305, tzinfo=utc)),
        ),
    ]
