# Generated by Django 2.1 on 2018-09-29 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180922_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
