# Generated by Django 2.1 on 2018-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercodechefauth',
            name='college_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercodechefauth',
            name='country_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercodechefauth',
            name='fullname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='usercodechefauth',
            name='global_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercodechefauth',
            name='occupation',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='usercodechefauth',
            name='organization',
            field=models.CharField(default='', max_length=256),
        ),
    ]
