# Generated by Django 2.1 on 2018-09-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20180925_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercodechefauth',
            name='college_rank',
        ),
        migrations.RemoveField(
            model_name='usercodechefauth',
            name='country_rank',
        ),
        migrations.RemoveField(
            model_name='usercodechefauth',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='usercodechefauth',
            name='global_rank',
        ),
        migrations.RemoveField(
            model_name='usercodechefauth',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='usercodechefauth',
            name='organization',
        ),
    ]
